### ISSUE TITLE
Include in quicklisp

### ISSUE THREAD

**Issue by justinmeiners** [telekons/one-more-re-nightmare#12]
I would be interested in accessing this through quicklisp. It may be there already but I didn't see it. Thanks.

**Comment by no-defun-allowed** [comment]
Can do, though I'd really like to use a POSIX ERE parser instead of this ad-hoc syntax before any "release" of any form. On the other hand, POSIX does not specify syntax for RE conjunction or negation. So I guess I'll have to roll forward with the current syntax for a while.

**Comment by justinmeiners** [comment]
I think most users of CL-PPCRE use the custom s-expression syntax rather than perl strings. I think nobody will complain if you only have your own s-expressions.

Btw im interested in your project because it looks like its the only Lisp implementation that actually generates DFAs.

**Comment by no-defun-allowed** [comment]
I've made the request: https://github.com/quicklisp/quicklisp-projects/issues/2142

**Comment by no-defun-allowed** [comment]
Looks like it's in the new dist.
