### ISSUE TITLE
Character classes

### ISSUE THREAD

**Issue by q3cpma** [telekons/one-more-re-nightmare#15]
Hello, and first, thanks a lot of for trying to make CL regexps faster (I come from https://github.com/mariomka/regex-benchmark/pull/43).

At first I wanted to emulate `\w` by using `[[:alnum:]_<other ranges>]` but I realized that simple disjoint character ranges (e.g. `[0-9a-z]`) were either unimplemented or had a different syntax.

So, is there a way to get this (other than `[[:alnum:]]` => `([a-z]|[A-Z]|[0-9])`? Related question, but what about POSIX characters classes and maybe more useful Unicode classes?

**Comment by no-defun-allowed** [comment]
I probably should implement disjoint character ranges, sure. But Unicode/POSIX character classes are tricky to implement, as they are huge unions of disjoint sets, which would not be wise to inline, as is done now. Such large sets should probably be stored in a kind of compressed bitmap, but I haven't thought it out yet. The compiler also has to reason about those sets too, which could get slow.

**Comment by no-defun-allowed** [comment]
Disjoint character ranges are implemented in 6d179cb7cc836f9644d8dfe829174a51af6ba5db; I'll still need a while to figure out a good way to handle large character classes.

**Comment by q3cpma** [comment]
On Sat, May 07, 2022 at 06:28:23PM -0700, Hayley Patton wrote:
> Disjoint character ranges are implemented in 2ff5c41; I'll still need a while to figure out a good way to handle large character classes.
>

Thanks a lot for your reactivity and effort.

**Comment by no-defun-allowed** [comment]
https://github.com/telekons/one-more-re-nightmare/wiki/Representing-character-classes has a sketch of how character classes may be represented.
