### ISSUE TITLE
Equivalent of ? and {n,m} for POSIX ERE feature parity

### ISSUE THREAD

**Issue by q3cpma** [telekons/one-more-re-nightmare#17]
Title says it all, having equivalents would be nice.

**Comment by no-defun-allowed** [comment]
They would. Baumann's paper mentions implementing both in terms of a generic "repetition" construct, which would be simpler than what we do now, even, so the current state of repetition is silly.

**Comment by no-defun-allowed** [comment]
Done with 73a949b.
