### ISSUE TITLE
Make character ranges inclusive

### ISSUE THREAD

**Issue by madnificent** [telekons/one-more-re-nightmare#19]
Character ranges currently seem to be exclusive, rather than inclusive of the last character.

```
> (all-string-matches "[a-b]" "a")
(#("a"))
> (ren:all-string-matches "[a-b]" "b")
nil
```

I don't think this is in line with POSIX and based on the examples I doubt it's intentional.  Can the range be made inclusive instead?

**Comment by madnificent** [comment]
Closing.  Can't reproduce with fresh lisp environment.  Works as expected now :thinking: :+1:

**Comment by no-defun-allowed** [comment]
This is indeed a bug with the version of OMRN that made it to the April Quicklisp release, which has been fixed since then.

**Comment by madnificent** [comment]
Ah, that explains!  The issues was gone after I cloned the repository in search for a fix.  In doing so I pulled in the fix.  Sanity restored.  Thank you.
