### ISSUE TITLE
CL-PPCRE compatible functions

### ISSUE THREAD

**Issue by phmarek** [telekons/one-more-re-nightmare#9]
It would be great if there were `CL-PPCRE` compatible functions, at least a few of them -- then it might be possible to just load `OMM` instead and provide `CL-PPCRE` as local nickname.

Eg. `ALL-MATCHES` has a different result format; perhaps that could be changed yet? Not sure whether a transforming function (to get compatibility) would be fast enough ;)

Thanks!

**Comment by no-defun-allowed** [comment]
I had considered such a feature, but I am not sure if that would be a good idea, as one-more-re-nightmare implements POSIX semantics (and a different regex syntax), so it cannot be plug compatible with CL-PPCRE, even if the interface was the same.
